### ISSUE TITLE
Options that weren't finalized might have unexpected consequences when MCT is reopened

### ISSUE THREAD

**Issue by paperpancake** [chadvandy/mod_configuration_tool#50]
This is a bit of an edge case. I think I'll be able to work around this for now using the MctPanelPopulated event, so you might just decide to close this issue and make it the modder's responsibility to handle this sort of thing. Still, it's one of those "gotcha" issues that would be nice to figure out for MX so that modders don't have to watch out for this edge case.

I have a dropdown that makes other options visible or invisible based on the current selection using `mct_option:add_option_set_callback`. This seems to be working except when:

1. The user changes the dropdown's setting (which changes the visibility of the other sections)
2. The user then closes MCT without finalizing.
3. The user then reopens my mod's panel in MCT. At this point, the dropdown reverts to the last finalized setting but doesn't trigger the dropdown's `mct_option:add_option_set_callback` (because the panel is populating). Because of that, all my other options don't update their visibility.

(The end user can work around this by now changing their selection to something else and then back again, which will trigger the callback and update the visibility, but it's not intuitive if they're not already familiar with how the dropdown visibility works.)

**Comment by paperpancake** [comment]
Just brainstorming an idea: This issue seems related to issues #30 and #34. Maybe we can piggyback on the solution for #34? MCT could avoid clearing the `option_obj._selected_setting` variable when the panel is closed and instead use it to determine if any option-set callbacks should be called when the panel is reopened?

**Comment by paperpancake** [comment]
Eh. I'm not sure anymore. Maybe it's best to make this the modder's responsibility and just mention in the documentation for `add_option_set_callback` that if a modder needs to alter state based on this selection, they should also check themselves in in MctPanelPopulated or some other event? Idk. What do you think?

**Comment by chadvandy** [comment]
I prevented add_option_set_callback from triggering on creation because of an infinite loop that's possible, yeah.

I think the best solution is to change how the callbacks work - change it to a listener (I made the add_option_set_callback before I decided on doing flexible events with listeners), and add a context for `context:is_creation()` or something to read if the option is being created initially or being changed later on. That way, MX is improved demonstrably with more control, it fits better with the listener-based systems set up, and all these issues can be resolved pretty easily.

Thoughts? I'd keep `option_obj:add_option_set_callback()`, I would just make it take a listener callback so you could do
```lua
option_obj:add_option_set_callback( 
    function(context)
        if context:is_creation() then --[[ do nothing]]
        else
            -- respond
        end
    end
)```

**Comment by chadvandy** [comment]
Incorporated "MctOptionSelectedSettingSet" as an event (mouthful), changed `mct_option:add_option_set_callback()` to send a full context to the callback, instead of just the mct_option. Backwards compatibility will have to be looked at here. #61
