### ISSUE TITLE
Make sure mct_option:set_uic_visibility doesn't destroy sort order

### ISSUE THREAD

**Issue by chadvandy** [chadvandy/mod_configuration_tool#78]

**Comment by paperpancake** [comment]
If you're thinking of filling in the gaps or something like that, please consider the use cases below where the gaps might be desired. If you do decide to fill in the gaps, I would ask that you provide a way for mods to opt-in or opt-out of filling in the gaps. or that you only do that before MctPanelPopulated so that modders can differentiate between when the gaps will be filled and when they won't.

Use cases:
1. My mods (AI General II, Find Idle Units) currently use this function to change visibility when users make selections, so the function needs to work even after the UI is created. (It's probably preferable if it doesn't change the sort order in this use case.)
2. I've been considering using permanently invisible options to provide UI spacing. I don't have this in any of my mods yet (I've been waiting to see if #56 adds dummy options or more UI control), so I'm not worried about backwards compatibility for my own sake. It's just something to think about when considering implementations.

**Comment by chadvandy** [comment]
Yeah I think it won't refresh when UI already exists, that could be clunky. Definitely want to leave a way to have blank spaces, whether that's an override on set visibility or a new "dummy option" I haven't really decided

**Comment by chadvandy** [comment]
Implemented with active_dev, this is only triggered before MctPanelPopulated (during mct_section:sort_options()) and won't be triggered again afterwards.
